version: '3.8'

services:
  bot:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./storage:/app/storage
    env_file:
      - .env
