const STATES = {
  IDLE: 'IDLE',
  AWAIT_ACCESS_PASSWORD: 'AWAIT_ACCESS_PASSWORD',
  AWAIT_CONSENT: 'AWAIT_CONSENT',
  AWAIT_FIO: 'AWAIT_FIO',
  AWAIT_REGION: 'AWAIT_REGION',
  AWAIT_SHOP_PAGE: 'AWAIT_SHOP_PAGE',
  AWAIT_ADMIN_SHOP_PAGE: 'AWAIT_ADMIN_SHOP_PAGE',
  AWAIT_DATE: 'AWAIT_DATE',
  AWAIT_ITEM: 'AWAIT_ITEM',
  AWAIT_EVENT_TYPE: 'AWAIT_EVENT_TYPE',
  AWAIT_VIOLATION_TYPE: 'AWAIT_VIOLATION_TYPE',
  AWAIT_AMOUNT: 'AWAIT_AMOUNT',
  AWAIT_PHOTO: 'AWAIT_PHOTO',
  AWAIT_CHECK_ACTION: 'AWAIT_CHECK_ACTION',
  AWAIT_MISSED_REASON: 'AWAIT_MISSED_REASON',
  AWAIT_TEXT_REPORT_FIO: 'AWAIT_TEXT_REPORT_FIO',
  AWAIT_TEXT_REPORT_DATE: 'AWAIT_TEXT_REPORT_DATE',
  AWAIT_TEXT_REPORT_TEXT: 'AWAIT_TEXT_REPORT_TEXT',
  CONFIRM: 'CONFIRM'
};

module.exports = { STATES };
